export const amenitiesList = [
  { id: 'wifi', label: 'WiFi', icon: '📶' },
  { id: 'kitchen', label: 'Kitchen', icon: '🍳' },
  { id: 'ac', label: 'Air Conditioning', icon: '❄️' },
  { id: 'heating', label: 'Heating', icon: '🔥' },
  { id: 'tv', label: 'TV', icon: '📺' },
  { id: 'washer', label: 'Washer', icon: '🧺' },
  { id: 'dryer', label: 'Dryer', icon: '👕' },
  { id: 'parking', label: 'Free Parking', icon: '🚗' },
  { id: 'pool', label: 'Swimming Pool', icon: '🏊' },
  { id: 'gym', label: 'Gym', icon: '💪' },
  { id: 'elevator', label: 'Elevator', icon: '⬆️' },
  { id: 'workspace', label: 'Dedicated Workspace', icon: '💼' },
  { id: 'pet_friendly', label: 'Pet Friendly', icon: '🐾' },
  { id: 'smoking', label: 'Smoking Allowed', icon: '🚬' },
  { id: 'security', label: 'Security Cameras', icon: '📹' },
  { id: 'fireplace', label: 'Fireplace', icon: '🔥' },
  { id: 'bbq', label: 'BBQ Grill', icon: '🍖' },
  { id: 'hot_tub', label: 'Hot Tub', icon: '🛁' },
];
